### ISSUE TITLE
Not working in Android "web app"

### ISSUE THREAD

**Issue by nomego** [GoogleWebComponents/google-signin#60]
When using the google-signin component / button for a mobile web app (Add to homescreen, start without browser controls, "web app" mode) the G+ sign-in doesn't work.
Pressing the button opens a new window in Chrome where the user can approve the G+ sign-in but after the authorization is complete, the user it not returned to the web app.

Is there any way to solve this ?

**Comment by Zoramite** [comment]
I think the original problem with this bug was an issue with iOS: http://stackoverflow.com/questions/25804730/window-close-doesnt-work-on-ios-8-gm-seed

My understanding is that the latest version (or upcoming release?) should fix the bug with the `window.close` not actually working correctly.

**Comment by nomego** [comment]
Well I don't have an iOS device right now, but it doesn't work with Android either.

**Comment by Zoramite** [comment]
Can you add more details about what you are seeing currently? Does the window just not close? If you manually close the window does it go back to the app and work normally? Does the immediate auth still work when you reload?

**Comment by nomego** [comment]
Well a new window opens in the browser, I get to the account chooser, choose an account and get to a blank page. 

Backing out of it and back to the app I'm not logged in, not after refreshing either. 

The pilot app referenced in the issue is still available if you want to try it yourself.

**Comment by fernandezpaco** [comment]
Same problem here, when you pack the signin component in a cordova app, the auth process happens in the same window and at the end the script tries to close the current window and fails.

I have this very basic example but you need to pack it with a cordova app: http://dynamicforms.paperplane.io/

It works fine in the browser but it fails at the end of the auth process when the script tries to close the window (that is the main window)

**Comment by fernandezpaco** [comment]
Basically the problem is described here:
http://phonegap-tips.com/articles/google-api-oauth-with-phonegaps-inappbrowser.html

The component supports signin for web apps but when packed as app it is not working because it should use a different mechanism (OAuth 2.0 for installed applications).

It would be awesome if the component supports both behaviors.

Thanks

**Comment by StephanBeutel** [comment]
Any news on this problem? I'm also fighting with this problem.

Would be great to get the component working in a cordova app.

**Comment by ManoBalaR** [comment]
Same Problem Here..

When using the google-signin component / button for a mobile web app (Add to homescreen, start without browser controls, "web app" mode) the G+ sign-in doesn't work.
Pressing the button opens a new window in Chrome where the user can approve the G+ sign-in but after the authorization is complete, the user it not returned to the web app.

Is there any way to solve this ?

**Comment by vamsi-manyam** [comment]
> Same Problem Here..
> 
> When using the google-signin component / button for a mobile web app (Add to homescreen, start without browser controls, "web app" mode) the G+ sign-in doesn't work.
> Pressing the button opens a new window in Chrome where the user can approve the G+ sign-in but after the authorization is complete, the user it not returned to the web app.
> 
> Is there any way to solve this ?

Hey did someone found the solution for this?

**Comment by ajaykmankani** [comment]
me too on the same page my google sign in working on a computer browser but not on an android chrome browser. anybody have any solutions?

**Comment by hieugia3030** [comment]
I am also facing this issue, has the problem been fixed yet?
